### ISSUE TITLE
Upstream PR

### ISSUE THREAD

**Issue by holiman** [kilic/eip2537#2]
Hi @kilic , 

Are you planning to make a PR for geth for EIP-2357? I don't want to do it on your behalf if you're already planning to do it, but for go-ethereum, it would be good to have a PR to start testing/verifying things.

**Comment by kilic** [comment]
@holiman Yes, I'm planning to make a PR for geth.

**Comment by kilic** [comment]
[PR](https://github.com/ethereum/go-ethereum/pull/21018) is sent. Closing.
